package com.example.meteortracker.ui.theme

import androidx.compose.ui.graphics.Color

val nasa_url_color = Color(0xFFB5EBFF)

//val md_theme_light_primary = Color(0xFF093872)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
//val md_theme_light_onPrimaryContainer = Color(0xFF001D34)
//val md_theme_light_secondary = Color(0xFF4758A9)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFDDE1FF)
//val md_theme_light_onSecondaryContainer = Color(0xFF001356)
//val md_theme_light_tertiary = Color(0xFF7564B1)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFD2E5F4)
//val md_theme_light_onTertiaryContainer = Color(0xFF0B1D29)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFCFCFF)
//val md_theme_light_onBackground = Color(0xFF1A1C1E)
//val md_theme_light_surface = Color(0xFFFCFCFF)
//val md_theme_light_onSurface = Color(0xFF1A1C1E)
//val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
//val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
//val md_theme_light_outline = Color(0xFF72777F)
//val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
//val md_theme_light_inverseSurface = Color(0xFF2F3033)
//val md_theme_light_inversePrimary = Color(0xFF9ACBFF)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFF00629E)
//val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
//val md_theme_light_scrim = Color(0xFF000000)

//--------------------------------------------------------------------------------------------------

val md_theme_light_primary = Color(0xFF4758A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001257)
val md_theme_light_secondary = Color(0xFF6451A5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE7DEFF)
val md_theme_light_onSecondaryContainer = Color(0xFF1F005F)
val md_theme_light_tertiary = Color(0xFF444CD7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0E0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF00006E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB9C3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4758A9)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)